services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: cd backend && chmod +x build.sh && ./build.sh
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
