services:
  - type: web
    name: gorakh-sawant-portfolio
    runtime: node
    buildCommand: |
      # Install frontend dependencies and build
      cd frontend
      npm install
      npm run build
      # Setup backend
      cd ../backend
      mkdir -p public
      cp -r ../frontend/build/* public/
      npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
